name = "SurfaceRegistration"
uuid = "6bd7b077-53e3-4ae0-9620-25197cb37145"
authors = ["Jørgen Riseth <jnriseth@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
